### ISSUE TITLE
How about the inference time?

### ISSUE THREAD

**Issue by zyl1336110861** [ADLab-AutoDrive/BEVFusion#1]
@ADLab-AutoDrive Thank you very much for your sharing! I am reading your paper and I am curious about the model inference time because you used the 2D-3D projection module.

**Comment by zyl1336110861** [comment]
Is it possible to be real-time?

**Comment by ADLab-AutoDrive** [comment]
It's not a real-time version now. The 2D-3D projection module is heavy. A possible way is to replace this part with BEVFormer.

**Comment by zyl1336110861** [comment]
@ADLab-AutoDrive Thank you for your response. I see that the BEVFormer can run about ~2FPS. So maybe it is still hard to make the BEVFusion model run fast?

**Comment by ADLab-AutoDrive** [comment]
Yes, it still takes a lot of effort to deploy BEVFusion into a car.

**Comment by tingtingliangvs** [comment]
Hi, inference time updates are in our latest [arxiv](https://arxiv.org/abs/2205.13790).
