### ISSUE TITLE
import 'ball_query_ext' issue

### ISSUE THREAD

**Issue by buaazeus** [ADLab-AutoDrive/BEVFusion#20]
I tried to train the model and got this issue.
cannot import name 'ball_query_ext' from partially initialized module 'mmdet3d.ops.ball_query'
Anyone has got and fixed this issue?
Thank you!

**Comment by hongweiliuideal** [comment]
hello，the environment is not compiled successfully, it is recommended to use **python setup.py develop** to compile successfully and then run the code

**Comment by buaazeus** [comment]
Issue is fixed. Thank you.

**Comment by zjufkq** [comment]
I also have this problem But it is not work

**Comment by zjufkq** [comment]
> hello，the environment is not compiled successfully, it is recommended to use **python setup.py develop** to compile successfully and then run the code

mmdet3d?

**Comment by buaazeus** [comment]
python setup.py develop in BEVFusion path.
