### ISSUE TITLE
Pretrain：about bevf_pp_4x8_2x_nusc_cam/epoch_24.pth，hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d/epoch_24.pth

### ISSUE THREAD

**Issue by hongweiliuideal** [ADLab-AutoDrive/BEVFusion#22]
Thanks for your great work！
Is that possible to provide：bevf_pp_4x8_2x_nusc_cam/epoch_24.pth，hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d/epoch_24.pth
I didn't find it in the readme.

**Comment by BlazingYoung** [comment]
Have you obtained these two files? Could you please share them with me:bevf_pp_4x8_2x_nusc_cam/epoch_24.pth and hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d/epoch_24.pth?
