### ISSUE TITLE
cannot import name 'ball_query_ext'

### ISSUE THREAD

**Issue by zjufkq** [ADLab-AutoDrive/BEVFusion#25]
I tried to train the model and got this issue.
cannot import name 'ball_query_ext' from partially initialized module 'mmdet3d.ops.ball_query'
I use   **python setup.py develop**   to compile mmdet3d , but it still doesn't work 
I have successfully installed mmdet3d==0.11.0 mmcv==1.4.0 mmdet == 2.11.0 
Anyone has got and fixed this issue?
Thank you!

**Comment by buaazeus** [comment]
run python setup.py develop in BEVFusion path, not mmdet3d.


first of all, uninstall mmdet3d as follows if you already compiled.
pip uninstall mmdet3d
rm -rf ./build
find . -name "*.so" | xargs rm
