### ISSUE TITLE
mmdet3d Version Incompatible

### ISSUE THREAD

**Issue by zjufkq** [ADLab-AutoDrive/BEVFusion#27]
I can't install mmdet3d=0.11.0 with the recommended version of torch=1.7.0 cuda=10.1 or 11.0. What's the matter? Or has anyone successfully configured the environment? thank
If I use torch=1.6.0, I can install mmdet3d==0.11.0, but code errors will occur in the end

**Comment by zjufkq** [comment]
I GOT IT

**Comment by mqm-slice** [comment]
So what version configuration did you use？Can you share with me?

**Comment by eyabesbes** [comment]
> I can't install mmdet3d=0.11.0 with the recommended version of torch=1.7.0 cuda=10.1 or 11.0. What's the matter? Or has anyone successfully configured the environment? thank If I use torch=1.6.0, I can install mmdet3d==0.11.0, but code errors will occur in the end

Hi,
I'm also facing the same problem?
how did you manage to solve the issue ?

**Comment by eyabesbes** [comment]
> So what version configuration did you use？Can you share with me?

Hi,
did you manage to configure the environment ?
