### ISSUE TITLE
NuImage-pretrained backbone and neck

### ISSUE THREAD

**Issue by VictorLlu** [ADLab-AutoDrive/BEVFusion#3]
Thanks for your great work! 
Is that possible to provide the nuImage-pretrained swin backbone and neck?

**Comment by tingtingliangvs** [comment]
Hi, I provide nuImage-pretrained detector in [readme](https://github.com/ADLab-AutoDrive/BEVFusion#:~:text=nuImage%20detection%20validation), hope it helps.
