### ISSUE TITLE
Differences in inference results

### ISSUE THREAD

**Issue by Young98CN** [ADLab-AutoDrive/BEVFusion#32]
This is a great job, but I have two questions 

1. There is a bug in running the [configuration file](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/bevf_tf_4x8_10e_nusc_aug.py).
The link to the bug is [here](https://github.com/ADLab-AutoDrive/BEVFusion/blob/c1cf4f2b018d89f289164d07f57a42d8bcfbfba3/mmdet3d/models/detectors/bevf_faster_rcnn_aug.py#L177)
`TypeError: forward() got an unexpected keyword argument 'extra_rots'`
3. Why I downloaded the pre-trained model that you [provided](https://drive.google.com/file/d/1wgcR6oYCrZvo3-whA5S4obTHce7aJ7OU/view?usp=share_link) and the inference results did not match the readme **NDS：72.1 mAP：69.6** . I got the result of **NDS：0.7132 mAP：0.6848** with [config](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/bevf_tf_4x8_6e_nusc.py)（Maybe I didn't find the difference between this configuration file and the above mentioned）

Looking forward to your reply ^_^

**Comment by Young98CN** [comment]
> This is a great job, but I have two questions
> 
> 1. There is a bug in running the [configuration file](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/bevf_tf_4x8_10e_nusc_aug.py).
> 2. Why I downloaded the pre-trained model that you [provided](https://drive.google.com/file/d/1wgcR6oYCrZvo3-whA5S4obTHce7aJ7OU/view?usp=share_link) and the inference results did not match the readme **NDS：72.1 mAP：69.6** . I got the result of **NDS：0.7132 mAP：0.6848** with [config](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/bevf_tf_4x8_6e_nusc.py)（Maybe I didn't find the difference between this configuration file and the above mentioned）
> 
> Looking forward to your reply ^_^

The link to the bug is [here](https://github.com/ADLab-AutoDrive/BEVFusion/blob/c1cf4f2b018d89f289164d07f57a42d8bcfbfba3/mmdet3d/models/detectors/bevf_faster_rcnn_aug.py#L177)
`TypeError: forward() got an unexpected keyword argument 'extra_rots'`

**Comment by Trent-tangtao** [comment]
Thank you for your interest!  It seems that the bugs are produced by reorganization of the code.
Besides, I forgot to update the code of camera branch and upload the wrong checkpoint. 
These problems have been fixed. You can pull the commits and  reload the checkpoint,  then rerun it now.

**Comment by Young98CN** [comment]
Thank you for your reply, but I noticed that the last update was five days ago, has the update been completed?

**Comment by Trent-tangtao** [comment]
Please checkout the dev_aug branch ~

**Comment by Young98CN** [comment]
Thanks for your patience, I will try it later! ^_^

**Comment by Young98CN** [comment]
Maybe there is a problem with my implementation, I got the result of NDS：0.7132 mAP：0.6848 with [config](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/bevf_tf_4x8_6e_nusc.py)(I load this [checkpoint](https://drive.google.com/file/d/1wgcR6oYCrZvo3-whA5S4obTHce7aJ7OU/view?usp=share_link) )

**Comment by Trent-tangtao** [comment]
Hi, I have updated the checkpoint. Do you download the new model checkpoint?

**Comment by Young98CN** [comment]
> Hi, I have updated the checkpoint. Do you download the new model checkpoint?

Oh, I downloaded the checkpoint under the main branch, Thanks for the reminder!

**Comment by Young98CN** [comment]
Thank you for your patient answer, I have got the accuracy in the readme, and I will close this issue.
