### ISSUE TITLE
Citation on BEV space augmentation

### ISSUE THREAD

**Issue by kentang-mit** [ADLab-AutoDrive/BEVFusion#33]
Dear authors,

I'm one of the contributors to another project named BEVFusion. I noticed that you added in BEV space augmentation following BEVDet and our work. Thanks for citing our work in your up-to-date arXiv paper. 

I wonder if it is possible to also reflect that you have referred to our code when adding this feature to your codebase in your README.md. There are discussions [here](https://github.com/mit-han-lab/bevfusion/issues/52) and [here](https://github.com/mit-han-lab/bevfusion/issues/22) back in June and July this year between me and the author who committed BEV space augmentation to this codebase, @Trent-tangtao.

I also found that the augmentation implementation in your dataset pipeline is the same as the implementation from our codebase (released a couple of months ago): lines 27-42 in [this file](https://github.com/ADLab-AutoDrive/BEVFusion/blob/a4dc33c364f0e5e0a0591a1423bba533449f7c64/mmdet3d/datasets/pipelines/transforms_3d.py#L27) corresponds to lines 134-155 in [this file](https://github.com/mit-han-lab/bevfusion/blob/071b457fdfc5d2be0a9bfe36c5ed17268746108f/mmdet3d/datasets/pipelines/transforms_3d.py#L134), lines 58-77 in [this file](https://github.com/ADLab-AutoDrive/BEVFusion/blob/a4dc33c364f0e5e0a0591a1423bba533449f7c64/mmdet3d/datasets/pipelines/transforms_3d.py#L58) corresponds to lines 253-272 in [this file](https://github.com/mit-han-lab/bevfusion/blob/dev/readme/mmdet3d/datasets/pipelines/transforms_3d.py#L134). Given the fact that our implementation is release much earlier than yours and we even release the training recipe way before your camera ready deadline, it would be greatly appreciated if you can consider acknowledging our work in this codebase. 

There is also a minor comment on how you cite our results in the camera-ready version (thanks again for mentioning our work). Would you mind also including the MACs of your method and ours in the table? An accuracy number alone is not helpful for the community to understand the efficiency-accuracy tradeoff of both methods. We would like to cite your paper and this number in our future arXiv update and I believe an official number will be helpful. By the way, the entry BEVFusion-base on the nuScenes [leaderboard](https://nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any) is from us, and it was made before your camera-ready deadline. It will also be great if you can update this entry to your arXiv paper.

Thank you very much and congratulations on the acceptance of your paper to NeurIPS 2022. Looking forward to your presentation at the conference.

Best,
Haotian

**Comment by Trent-tangtao** [comment]
Hi Haotian,

Thanks for your great efforts and the discussions with me.
As mentioned in our camera-ready version, we conduct BEV-space data augmentation following [[BEVDet](https://arxiv.org/abs/2112.11790)](https://arxiv.org/abs/2112.11790) and [[BEVFusion-mit](https://github.com/mit-han-lab/bevfusion)](https://github.com/mit-han-lab/bevfusion)(yours). And the arXiv paper will be updated later.
Sorry for my negligence to add the acknowledging of referenced implementations in our README.md of the codebase and I have updated it just now.
Thanks again for your attractive works and the great open-sourced code base.

Best,
Tangtao

**Comment by kentang-mit** [comment]
Hi Tao,

Thank you very much! It's very helpful, and looking forward to your new arXiv version. I'll close this issue now.

Best,
Haotian

**Comment by kentang-mit** [comment]
Dear authors,

When should I expect your new arXiv version? If you haven't finished, it would be greatly appreciated if you can discuss with us (Zhijian and me) about the paper update via Email next week such that we can avoid unnecessary back and forth. We'd like to see Prof. Wang and Prof. Tang involved in the discussion. Thanks for your time!

Best,
Haotian

**Comment by tingtingliangvs** [comment]
Hi Haotian,

I have updated the arXiv and you will see the changes soon.
In the camera-ready version we uploaded to the NeurIPS system,  we didn't use the '70.2 mAP 72.9 NDS' MIT-Base version. Sorry for the trouble.

Best,
Tingting

**Comment by kentang-mit** [comment]
Thank you @tingtingliangvs. We'll check the new content in the updated arXiv version and see if further discussions are needed. Have a nice day!
