### ISSUE TITLE
KeyError: 'MindFreeHook is not in the hook registry'

### ISSUE THREAD

**Issue by hz3014** [ADLab-AutoDrive/BEVFusion#38]
I was running command 

> ./tools/dist_train.sh configs/bevfusion/cam_stream/bevf_tf_4x8_20e_nusc_cam_lr.py 8

and I had following error:

> noise setting:
> models/mask_rcnn_dbswin-t_fpn_3x_nuim_cocopre.pth
> /workspace/BEVFusion/mmdetection-2.11.0/mmdet/apis/train.py:95: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
>   warnings.warn(
> noise setting:
> Traceback (most recent call last):
>   File "tools/train.py", line 316, in <module>
>     main()
>   File "tools/train.py", line 305, in main
>     train_detector(
>   File "/workspace/BEVFusion/mmdetection-2.11.0/mmdet/apis/train.py", line 163, in train_detector
>     hook = build_from_cfg(hook_cfg, HOOKS)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
>     raise KeyError(
> KeyError: 'MindFreeHook is not in the hook registry'

It seems to be able to train after i comment the custom hook. I do not find information about MindFreeHook in the repo abd I was wondering what does it do? and does it affect performance if i comment it?

**Comment by Trent-tangtao** [comment]
Hi,
You can comment out these lines of code directly. The hook is used to debug without affecting performance.
