### ISSUE TITLE
loss:NAN or loss does not decline

### ISSUE THREAD

**Issue by quchunyan** [ADLab-AutoDrive/BEVFusion#48]
Hello, good job.
When i was training the camera branch with nuscenes dataset, two problems occurred:
(1)loss didn't decline
(2)when i use img_depth， loss became nan after serveral iters.

**Comment by ztf-ucas** [comment]
Is the problem solved?

**Comment by ztf-ucas** [comment]
Is the problem solved? I had the same problem, loss became nan after serveral iters with img_depth.

**Comment by HaoZhang16613** [comment]
@quchunyan Hi~ Is the problem solved? I had the same problem, loss became nan after serveral iters with img_depth.
I've already tried some solutions, like adding img_depth loss after a few training epoches and setting img_depth loss to zero when it is abnormal ... Unfortunately, all solutions didn't work.
