### ISSUE TITLE
about camera calibration

### ISSUE THREAD

**Issue by MasatoSaeki** [ADLab-AutoDrive/BEVFusion#5]
Thank you for your working.

1.
https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/mmdet3d/models/detectors/bevf_faster_rcnn.py#L126
2.
https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/mmdet3d/models/detectors/cam_stream_lss.py#L311

In 1., the projection matrix is passed, but in 2., it looks like it is not used.
Do you use this kind of camera calibration when projecting to BEV?
(In original liftsplatshoot, that is used)

**Comment by tingtingliangvs** [comment]
Hi, we use camera extrinsic parameters 'rots' and 'trans' when projecting to BEV. Since no data augmentation is used, we do not need to recover 'post_trans' and 'post_rots'.

**Comment by jcuic5** [comment]
Hi, I also have a question. Since 'rots' and 'trans' are extrinsic transformations, doesn't it still needs the intrinsics to perform the projection? Seems the pre-generated frustum grid is with pixel coordinate values

**Comment by MasatoSaeki** [comment]
Thank you very much.

**Comment by hrz2000** [comment]
> Hi, we use camera extrinsic parameters 'rots' and 'trans' when projecting to BEV. Since no data augmentation is used, we do not need to recover 'post_trans' and 'post_rots'.

In LSS's code：
![image](https://user-images.githubusercontent.com/79900945/193190914-ba49f7e2-4266-40ce-89f1-809c37a57ab9.png)

but your code don‘t have the ‘intrins’，why？

**Comment by zhanghaozhe23** [comment]
Have you solved the problem?
