### ISSUE TITLE
How to get the BEV feature of Lidar?

### ISSUE THREAD

**Issue by sunnyHelen** [ADLab-AutoDrive/BEVFusion#6]
Hi, thanks a lot for sharing your great work! 
I'm new to the 3D detection field. After reading your paper and the code, I didn't understand how to get the BEV feature of Lidar (e.g. using transfusion). I got the BEV feature of images obtained via the Lift-splat manner but didn't get the way getting the BEV feature of Lidar. From my reading of the code, it seems that there is no transformation of point cloud to BEV space.
Could you please help me figure it out?

**Comment by tingtingliangvs** [comment]
Hi, TransFusion originally conducts detection on BEV space. [pts_feats](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/mmdet3d/models/detectors/bevf_faster_rcnn.py#L126:~:text=pts_feats%20%3D%20self.extract_pts_feat(points%2C%20img_feats%2C%20img_metas)) is LiDAR BEV feature.
