### ISSUE TITLE
gpu memory

### ISSUE THREAD

**Issue by shanguangcv** [ADLab-AutoDrive/BEVFusion#7]
Hi, how much memory does the training network need? Is 16g OK? How long does 8v100 (16g) need training? Thanks!

**Comment by zjufkq** [comment]
> 

Dou you mean a card(v100) needs about 2 days for each, and joint training needs about 10 hours?

**Comment by tingtingliangvs** [comment]
Yeah, for PointPillars. It needs more time (about 6 days) to train the LiDAR detector of TransFusion.
